from space_functions import dms_to_decimal

# Global launch site latitudes in decimal degrees
CAPE_CANAVERAL      = dms_to_decimal(28, 30, hemisphere='N')
VANDENBERG          = dms_to_decimal(34, 36, hemisphere='N')
WALLOPS_ISLAND      = dms_to_decimal(37, 48, hemisphere='N')
KWAJALEIN_ATOLL     = dms_to_decimal(9, 3, hemisphere='N')
KODIAK_ISLAND       = dms_to_decimal(57, 25, hemisphere='N')
BAIKONUR            = dms_to_decimal(45, 54, hemisphere='N')
PLESETSK            = dms_to_decimal(62, 48, hemisphere='N')
KAPUSTIN_YAR        = dms_to_decimal(48, 24, hemisphere='N')
VOSTOCHNY           = dms_to_decimal(51, 53, hemisphere='N')
KOUROU              = dms_to_decimal(5, 32, hemisphere='N')
TANEGASHIMA         = dms_to_decimal(30, 14, hemisphere='N')
SRIHARIKOTA         = dms_to_decimal(13, 47, hemisphere='N')
JIUQUAN             = dms_to_decimal(40, 25, hemisphere='N')
XICHANG             = dms_to_decimal(28, 6, hemisphere='N')
TAIYUAN             = dms_to_decimal(38, 40, hemisphere='N')
WENCHANG            = dms_to_decimal(19, 37, hemisphere='N')
YAVNE               = dms_to_decimal(31, 31, hemisphere='N')
ALCANTARA           = dms_to_decimal(2, 17, hemisphere='S')
MAHIA_PENINSULA     = dms_to_decimal(39, 16, hemisphere='S')
ARNHEM_LAND         = dms_to_decimal(12, 23, hemisphere='S')
WHALERS_WAY         = dms_to_decimal(34, 30, hemisphere='S')
NINGBO              = dms_to_decimal(29, 50, hemisphere='N')
